### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AFluffyOrangutan** [akbaryahya/PokeBot#1]
[08:32:49] Update stats ok
[08:32:50] Update item ok
[08:32:50] Stoping to Cek EGG Pokemon.
[08:32:53] Egg (2km) need to walk 0.26 km.
[08:32:53] Egg (10km) need to walk 8.56 km.
[08:32:53] Egg (5km) need to walk 3.6 km.
[08:32:53] Cek EGG Pokemon done. Time to continue our journey!
[08:32:53] Stoping to evolve some Pokemons.
[08:32:54] Pokemons evolved. Time to continue our journey!
[08:32:54] Stoping to Transfer some Pokemons.
[08:32:56] Transfer Pokemons done. Time to continue our journey!
[08:32:56] Stoping to Recycle item.
[08:32:57] Recycle item done. Time to continue our journey!
[08:32:58] Incense still running: 28m8s
[08:32:58] NullReferenceException: System.NullReferenceException: Object reference not set to an instance of an object.
   at PokemonGo.RocketAPI.Logic.Logic.<cekpokerare>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<ExecuteFarmingPokestopsAndPokemons>d__63.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<PostLoginExecute>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PokemonGo.RocketAPI.Logic.Logic.<Execute>d__54.MoveNext()

**Comment by akbaryahya** [comment]
can you give full log? but I think problem is in incense, I'll check it later

**Comment by AFluffyOrangutan** [comment]
Yea sure. Here you go,
[log.txt](https://github.com/akbaryahya/PokeBot/files/679065/log.txt)

**Comment by akbaryahya** [comment]
try the update again, I hope the problem is solved
