### ISSUE TITLE
Pb with bot 6.0

### ISSUE THREAD

**Issue by Titiocb13** [akbaryahya/PokeBot#24]
![image](https://cloud.githubusercontent.com/assets/24854765/22655947/11799974-ec92-11e6-8814-d7895d618f5b.png)

**Comment by akbaryahya** [comment]
can you give full error log? if still problem

**Comment by Titiocb13** [comment]
this is the full log :
[06:41:37] ============================================================================
[06:41:37] ______     ______    __  ___  _______ .______     ______   .___________.   =
[06:41:37] |   _  \   /  __  \  |  |/  / |   ____||   _  \   /  __  \  |           |  =
[06:41:37] |  |_)  | |  |  |  | |  '  /  |  |__   |  |_)  | |  |  |  | `---|  |----`  =
[06:41:37] |   ___/  |  |  |  | |    <   |   __|  |   _  <  |  |  |  |     |  |       =
[06:41:37] |  |      |  `--'  | |  .  \  |  |____ |  |_)  | |  `--'  |     |  |       =
[06:41:37] | _|       \______/  |__|\__\ |_______||______/   \______/      |__|       =
[06:41:37] ============================================================================
[06:41:37] ~ Cek update...., if it does not show anything, try to restart it!!!
[06:41:38] ~ You have last update
[06:41:59] ~ Send info pokemon,gym,pokestop, Thanks for helping us ^_^
[06:41:59] ~ Get last location, try to remove and then start new location
[06:41:59] ~ Your speed is too fast, beware banned. Now: 130km/h
[06:41:59] ~ Egg will not work if speed is more 20km/h. Now: 130km/h
[06:41:59] ~ Use NEW API: 0.55.0 POGO
[06:41:59] -> If you understand!!!, please press any key to continue OR 'n' to close <-
[06:42:01] Starting login: Ptc
[06:42:03] Big problem happened, Restart in 8 Seconds.
[06:42:11] Big problem happened, Restart in 8 Seconds.

**Comment by Titiocb13** [comment]
in debug mode : 
[14:47:32] ~ Cek update...., if it does not show anything, try to restart it!!!
[14:47:33] ~ Update available!
[14:48:35] ============================================================================
[14:48:35] ______     ______    __  ___  _______ .______     ______   .___________.   =
[14:48:35] |   _  \   /  __  \  |  |/  / |   ____||   _  \   /  __  \  |           |  =
[14:48:35] |  |_)  | |  |  |  | |  '  /  |  |__   |  |_)  | |  |  |  | `---|  |----`  =
[14:48:35] |   ___/  |  |  |  | |    <   |   __|  |   _  <  |  |  |  |     |  |       =
[14:48:35] |  |      |  `--'  | |  .  \  |  |____ |  |_)  | |  `--'  |     |  |       =
[14:48:35] | _|       \______/  |__|\__\ |_______||______/   \______/      |__|       =
[14:48:35] ============================================================================
[14:48:35] ~ Cek update...., if it does not show anything, try to restart it!!!
[14:48:37] ~ You have last update
[14:49:07] ~ Send info pokemon,gym,pokestop, Thanks for helping us ^_^
[14:49:07] ~ Get last location, try to remove and then start new location
[14:49:07] ~ Your speed is too fast, beware banned. Now: 130km/h
[14:49:07] ~ Egg will not work if speed is more 20km/h. Now: 130km/h
[14:49:08] ~ Use NEW API: 0.55.0 POGO
[14:49:08] -> If you understand!!!, please press any key to continue OR 'n' to close <-
[14:49:13] Starting login: Ptc
[14:49:18] Big problem happened, Restart in 8 Seconds.
[14:49:18] Error: System.MissingMethodException: Méthode introuvable : 'Void POGOProtos.Networking.Requests.Request.set_RequestMessage(Google.Protobuf.ByteString)'.
   à PokemonGo.RocketAPI.Rpc.Player.GetPlayer(Boolean addCommonRequests)
   à PokemonGo.RocketAPI.Rpc.Login.DoLogin() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Rpc\Login.cs:ligne 162
   à PokemonGo.RocketAPI.Logic.Logic.Execute()
[14:49:27] Big problem happened, Restart in 8 Seconds.
[14:49:27] Error: System.MissingMethodException: Méthode introuvable : 'Void POGOProtos.Networking.Requests.Request.set_RequestMessage(Google.Protobuf.ByteString)'.
   à PokemonGo.RocketAPI.Rpc.Player.GetPlayer(Boolean addCommonRequests)
   à PokemonGo.RocketAPI.Rpc.Login.DoLogin() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Rpc\Login.cs:ligne 162
   à PokemonGo.RocketAPI.Logic.Logic.Execute()

**Comment by Titiocb13** [comment]
With the last commit Pokebot.exe :


[15:12:26] ============================================================================
[15:12:26] ______     ______    __  ___  _______ .______     ______   .___________.   =
[15:12:26] |   _  \   /  __  \  |  |/  / |   ____||   _  \   /  __  \  |           |  =
[15:12:26] |  |_)  | |  |  |  | |  '  /  |  |__   |  |_)  | |  |  |  | `---|  |----`  =
[15:12:26] |   ___/  |  |  |  | |    <   |   __|  |   _  <  |  |  |  |     |  |       =
[15:12:26] |  |      |  `--'  | |  .  \  |  |____ |  |_)  | |  `--'  |     |  |       =
[15:12:26] | _|       \______/  |__|\__\ |_______||______/   \______/      |__|       =
[15:12:26] ============================================================================
[15:12:26] ~ Cek update...., if it does not show anything, try to restart it!!!
[15:12:28] ~ You have last update
[15:12:37] ~ Send info pokemon,gym,pokestop, Thanks for helping us ^_^
[15:12:37] ~ Get last location, try to remove and then start new location
[15:12:37] ~ Your speed is too fast, beware banned. Now: 130km/h
[15:12:37] ~ Egg will not work if speed is more 20km/h. Now: 130km/h
[15:12:38] ~ Use NEW API: 0.55.0 POGO
[15:12:38] -> If you understand!!!, please press any key to continue OR 'n' to close <-
[15:12:40] Starting login: Ptc
[15:12:43] Big problem happened, Restart in 8 Seconds.
[15:12:43] Error: System.MissingMethodException: Méthode introuvable : 'Void POGOProtos.Networking.Requests.Request.set_RequestMessage(Google.Protobuf.ByteString)'.
   à PokemonGo.RocketAPI.Rpc.Player.GetPlayer(Boolean addCommonRequests)
   à PokemonGo.RocketAPI.Rpc.Login.DoLogin() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Rpc\Login.cs:ligne 162
   à PokemonGo.RocketAPI.Logic.Logic.Execute()
[15:12:53] Big problem happened, Restart in 8 Seconds.
[15:12:53] Error: System.MissingMethodException: Méthode introuvable : 'Void POGOProtos.Networking.Requests.Request.set_RequestMessage(Google.Protobuf.ByteString)'.
   à PokemonGo.RocketAPI.Rpc.Player.GetPlayer(Boolean addCommonRequests)
   à PokemonGo.RocketAPI.Rpc.Login.DoLogin() dans C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Rpc\Login.cs:ligne 162
   à PokemonGo.RocketAPI.Logic.Logic.Execute()

**Comment by Titiocb13** [comment]
Hi, with the dll, one per hour i have 👍 
[19:21:45] Error: Google.Protobuf.InvalidProtocolBufferException: SkipLastField called on an end-group tag, indicating that the corresponding start-group was missing
   à Google.Protobuf.CodedInputStream.SkipLastField()
   à POGOProtos.Networking.Envelopes.ResponseEnvelope.MergeFrom(CodedInputStream input)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.PerformRemoteProcedureCall[TRequest](Client apiClient, RequestEnvelope requestEnvelope)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.PerformThrottledRemoteProcedureCall[TRequest](Client apiClient, RequestEnvelope requestEnvelope)
   à PokemonGo.RocketAPI.Extensions.HttpClientExtensions.PostProtoPayload[TRequest](Client apiClient, RequestEnvelope requestEnvelope, Type[] responseTypes)
   à PokemonGo.RocketAPI.Rpc.BaseRpc.PostProtoPayload[TRequest,T1,T2](RequestEnvelope requestEnvelope)
   à PokemonGo.RocketAPI.Rpc.Player.UpdatePlayerLocation(Double latitude, Double longitude, Double altitude, Single speed)
   à PokemonGo.RocketAPI.Logic.Logic.HumanLikeWalking(GeoCoordinate targetLocation, Double walkingSpeedInKilometersPerHour, Boolean trackpoke, Boolean fromgoogle, Boolean stopat)
   à PokemonGo.RocketAPI.Logic.Logic.DoRouteWalking(Double latitude, Double longitude, Double walkspeed)
   à PokemonGo.RocketAPI.Logic.Logic.MultiWalkp()
   à PokemonGo.RocketAPI.Logic.Logic.ExecuteFarmingPokestopsAndPokemons(Boolean ulanglokasi, Boolean pokestop, Boolean pokemon, Boolean gysm, Double lat, Double lot, Boolean loadmap)
   à PokemonGo.RocketAPI.Logic.Logic.Execute()

But the bot restart correctly

**Comment by akbaryahya** [comment]
can you give full tmp/log.txt ? I want to know where the error,what he is doing at that time

**Comment by Titiocb13** [comment]
full log =>
[log.txt](https://github.com/akbaryahya/PokeBot/files/758879/log.txt)

**Comment by Titiocb13** [comment]
22:16:53] Soft Ban Detected - Stopping Bot to prevent perma-ban. Try again in 4-24 hours and be more careful next time!
[22:16:53] Use Default Speed
[22:16:53] Return to starting location Default
[22:16:55] Found 1 catchable Pokemon(s): Paras
[22:16:56] Encountered: Paras | CP 424 | IV 57,78% | LV 20 | M1:ScratchFast M2:CrossPoison | A:6 D:8 S:12 | 43.952748, 4.805455 | -1
[22:16:58] Nice throw as Curve ball.
[22:16:59] Paras got away while using ItemPokeBall...
[22:16:59] Soft Ban Detected - Stopping Bot to prevent perma-ban. Try again in 4-24 hours and be more careful next time!
[22:16:59] Use Default Speed
[22:16:59] Return to starting location Default
[22:17:08] Now bot stop, bye bye bye

**Comment by akbaryahya** [comment]
you try snipe or just go away 10x?

**Comment by Titiocb13** [comment]
Not snipe. Just walk speed between 110 and 130.
But wirh bot version 1.5.9, i had same parameters and never had soft ban.

**Comment by Titiocb13** [comment]
look the next logs, i was soft banned on 22:07:51 
[22:07:51] Magmar got away while using ItemUltraBall...

At 22:07:53, i wasn't banned :
[22:07:39] Missed Jynx while using ItemUltraBall
[22:07:42] Not wasting more of your Ultra Balls! Forcing a hit on target.
[22:07:42] Excellent throw as Curve ball.
[22:07:43] Caught Jynx using ItemUltraBall got 210 XP.


ma i soft banned because bot forcing a hit on a target ?


then after i had lot of "pokemon got away" during 10 minuts and the bot stopped.

Complete log =>
[ban_log.txt](https://github.com/akbaryahya/PokeBot/files/760108/ban_log.txt)

**Comment by orignguyen** [comment]
I'm trying the bot and have the same fault. The log as below:

[14:10:43] ~ You have last update
[14:11:09] ~ Send info pokemon,gym,pokestop, Thanks for helping us ^_^
[14:11:09] ~ Get last location, try to remove and then start new location
[14:11:10] ~ API BOT: 0.45.0 ~ API POGO: 0.55.0 -> Not safe, continued use you will force use old api
[14:11:10] -> If you understand!!!, please press any key to continue OR 'n' to close <-
[14:11:14] Starting login: Ptc
[14:11:16] Big problem happened, Restart in 8 Seconds.
[14:11:16] Error: System.MissingMethodException: Method not found: 'Void POGOProtos.Networking.Requests.Request.set_RequestMessage(Google.Protobuf.ByteString)'.
   at PokemonGo.RocketAPI.Rpc.Player.GetPlayer(Boolean addCommonRequests)
   at PokemonGo.RocketAPI.Rpc.Login.DoLogin() in C:\Users\siakbary\Documents\Works\MyCode\PokemonGo.RocketAPI\Rpc\Login.cs:line 162
   at PokemonGo.RocketAPI.Logic.Logic.Execute()
[14:11:26] Big problem happened, Restart in 8 Seconds.

**Comment by Titiocb13** [comment]
Download the dll package and put them on poke bot directory

**Comment by orignguyen** [comment]
Thanks so much. I'' try again.


________________________________
